#!/bin/bash
# Generate a structured CHANGELOG.md from git history
# Usage: ./changelog.sh [output-file]
# Works as: /generate-changelog in Claude Code

set -e

OUTPUT="${1:-CHANGELOG.md}"

echo "📝 Generating CHANGELOG.md..."
echo "# Changelog" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "All notable changes to this project will be documented in this file." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Get the last tag, or use initial commit
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
CURRENT_TAG=$(git describe --tags 2>/dev/null || echo "v0.1.0")

if [ -z "$LAST_TAG" ]; then
    echo "## [unreleased]" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    # Categorize commits
    git log --pretty=format:"%s" --no-merges 2>/dev/null | while IFS= read -r msg; do
        category="Changed"
        if echo "$msg" | grep -qiE '^(feat|add|new|create|implement)'; then
            category="Added"
        elif echo "$msg" | grep -qiE '^(fix|bug|hotfix|patch)'; then
            category="Fixed"
        elif echo "$msg" | grep -qiE '^(remove|delete|drop|deprecate)'; then
            category="Removed"
        fi
        echo "### $category" >> "$OUTPUT"
        echo "- $msg" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
    done
else
    echo "## [$CURRENT_TAG] - $(git log -1 --format=%as "$CURRENT_TAG" 2>/dev/null || date +%Y-%m-%d)" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    
    # Categorize commits since last tag
    git log "$LAST_TAG..HEAD" --pretty=format:"%s" --no-merges 2>/dev/null | while IFS= read -r msg; do
        category="Changed"
        if echo "$msg" | grep -qiE '^(feat|add|new|create|implement)'; then
            category="Added"
        elif echo "$msg" | grep -qiE '^(fix|bug|hotfix|patch)'; then
            category="Fixed"
        elif echo "$msg" | grep -qiE '^(remove|delete|drop|deprecate)'; then
            category="Removed"
        fi
        echo "### $category" >> "$OUTPUT"
        echo "- $msg" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
    done
fi

# Add support section
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "> 💖 Generated by [changelog.sh](https://github.com/feezy1357/useful-scripts)" >> "$OUTPUT"
echo "> Support this project: https://feezy1357.github.io/tools-collection/" >> "$OUTPUT"

echo "✅ CHANGELOG.md generated successfully!"
