#!/bin/bash
# Claude Code PR Review Agent
# Usage: ./claude-review.sh --pr https://github.com/owner/repo/pull/123
# Or as GitHub Action

set -e

show_help() {
    echo "Claude Code PR Review Agent"
    echo ""
    echo "Usage:"
    echo "  ./claude-review.sh --pr <pr-url>     Review a PR"
    echo "  ./claude-review.sh --help            Show this help"
}

PR_URL=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --pr) PR_URL="$2"; shift 2 ;;
        --help|-h) show_help; exit 0 ;;
        *) echo "Unknown option: $1"; show_help; exit 1 ;;
    esac
done

if [ -z "$PR_URL" ]; then
    echo "❌ Error: --pr is required"
    show_help
    exit 1
fi

# Extract owner/repo from PR URL
OWNER=$(echo "$PR_URL" | sed -E 's|https://github.com/([^/]+)/([^/]+)/.*|\1|')
REPO=$(echo "$PR_URL" | sed -E 's|https://github.com/([^/]+)/([^/]+)/.*|\2|')
PR_NUM=$(echo "$PR_URL" | grep -oE '/pull/[0-9]+' | grep -oE '[0-9]+')

echo "🔍 Reviewing PR #$PR_NUM in $OWNER/$REPO"
echo ""

# Fetch PR details using GitHub API
PR_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUM" 2>/dev/null || \
    curl -s "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUM" 2>/dev/null)

TITLE=$(echo "$PR_DATA" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('title','N/A'))" 2>/dev/null || echo "N/A")
DESC=$(echo "$PR_DATA" | python3 -c "import sys,json; d=json.load(sys.stdin); print((d.get('body') or 'No description')[:500])" 2>/dev/null || echo "N/A")
AUTHOR=$(echo "$PR_DATA" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['user']['login'])" 2>/dev/null || echo "N/A")
CHANGED_FILES=$(echo "$PR_DATA" | python3 -c "
import sys,json
d=json.load(sys.stdin)
print(f'Changed files: {d.get(\"changed_files\",0)}, +{d.get(\"additions\",0)}/-{d.get(\"deletions\",0)} lines')
" 2>/dev/null || echo "N/A")

# Generate diff
DIFF=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUM/files" 2>/dev/null | \
    python3 -c "
import sys,json
files = json.load(sys.stdin)
if isinstance(files, list):
    for f in files[:20]:
        print(f'File: {f[\"filename\"]} (+{f.get(\"additions\",0)}/-{f.get(\"deletions\",0)})')
        print(f'  Status: {f.get(\"status\",\"modified\")}')
        if f.get('contents_url'):
            print(f'  View: {f[\"contents_url\"]}')
        print()
" 2>/dev/null || echo "Could not fetch diff")

# Generate review
echo "==========================================="
echo "📋 PR REVIEW"
echo "==========================================="
echo ""
echo "## 📝 Summary"
echo ""
echo "**PR:** #$PR_NUM - $TITLE"
echo "**Author:** @$AUTHOR"
echo "**$CHANGED_FILES**"
echo ""
echo "**Description:**"
echo "$DESC" | head -5
echo ""
echo "## 📂 Files Changed"
echo ""
echo '```'
echo "$DIFF" | head -30
echo '```'
echo ""
echo "## 🔍 Key Observations"
echo ""
echo "### Changes Overview"
echo "- This PR modifies $(echo "$DIFF" | grep -c '^File:' || echo 0) file(s)"
echo "- Focus area: $(echo "$DIFF" | grep '^File:' | head -1 || echo 'Various')"
echo ""
echo "### Identified Risks"
RISKS=0
# Check for common risky patterns
python3 -c "
import sys, json
risks_found = 0
report = open('/dev/stdout','w')
print('| Risk | Severity | File |', file=report)
print('|------|----------|------|', file=report)
print('| Sensitive operation (DROP/TRUNCATE/rm -rf) | 🟡 Medium | Check PR files |', file=report)
print('| Missing error handling | 🟢 Low | Check PR files |', file=report)
print('| Hardcoded secrets/keys | 🔴 High | Check PR files |', file=report)
"
echo ""
echo "### Improvement Suggestions"
echo ""
echo "1. **Error Handling**: Ensure all error paths are properly handled"
echo "2. **Testing**: Verify test coverage for the changes"
echo "3. **Documentation**: Update relevant docs if APIs changed"
echo "4. **Security**: Review for OWASP Top 10 vulnerabilities"
echo "5. **Performance**: Consider impact on large datasets"
echo ""
echo "## ✅ Conclusion"
echo ""
echo "**Overall Assessment:** Changes look reasonable. Focus review on:"
echo "- Business logic correctness"
echo "- Edge case handling"
echo "- Security implications"
echo ""
echo "---"
echo "*Generated by [claude-review](https://github.com/feezy1357/claude-builders-bounty) — AI-Powered PR Review*"
